// Countries players and coaches can come from.
//   code: 2-letter ISO code. This is what we store in the database (and what flag images use).
//   ioc:  3-letter code tennis scoreboards show, e.g. KAZ, POL, SUI.
// This file is used by the browser AND by the server (for checking codes), so it's written
// to work in both places (see the last lines).
const COUNTRIES = [
  { code: 'AR', name: "Argentina", ioc: 'ARG' },
  { code: 'AU', name: "Australia", ioc: 'AUS' },
  { code: 'AT', name: "Austria", ioc: 'AUT' },
  { code: 'BY', name: "Belarus", ioc: 'BLR' },
  { code: 'BE', name: "Belgium", ioc: 'BEL' },
  { code: 'BO', name: "Bolivia", ioc: 'BOL' },
  { code: 'BA', name: "Bosnia and Herzegovina", ioc: 'BIH' },
  { code: 'BR', name: "Brazil", ioc: 'BRA' },
  { code: 'BG', name: "Bulgaria", ioc: 'BUL' },
  { code: 'CA', name: "Canada", ioc: 'CAN' },
  { code: 'CL', name: "Chile", ioc: 'CHI' },
  { code: 'CN', name: "China", ioc: 'CHN' },
  { code: 'TW', name: "Chinese Taipei", ioc: 'TPE' },
  { code: 'CO', name: "Colombia", ioc: 'COL' },
  { code: 'HR', name: "Croatia", ioc: 'CRO' },
  { code: 'CY', name: "Cyprus", ioc: 'CYP' },
  { code: 'CZ', name: "Czechia", ioc: 'CZE' },
  { code: 'DK', name: "Denmark", ioc: 'DEN' },
  { code: 'EC', name: "Ecuador", ioc: 'ECU' },
  { code: 'EG', name: "Egypt", ioc: 'EGY' },
  { code: 'EE', name: "Estonia", ioc: 'EST' },
  { code: 'FI', name: "Finland", ioc: 'FIN' },
  { code: 'FR', name: "France", ioc: 'FRA' },
  { code: 'GE', name: "Georgia", ioc: 'GEO' },
  { code: 'DE', name: "Germany", ioc: 'GER' },
  { code: 'GB', name: "Great Britain", ioc: 'GBR' },
  { code: 'GR', name: "Greece", ioc: 'GRE' },
  { code: 'HK', name: "Hong Kong", ioc: 'HKG' },
  { code: 'HU', name: "Hungary", ioc: 'HUN' },
  { code: 'IN', name: "India", ioc: 'IND' },
  { code: 'ID', name: "Indonesia", ioc: 'INA' },
  { code: 'IE', name: "Ireland", ioc: 'IRL' },
  { code: 'IL', name: "Israel", ioc: 'ISR' },
  { code: 'IT', name: "Italy", ioc: 'ITA' },
  { code: 'JP', name: "Japan", ioc: 'JPN' },
  { code: 'KZ', name: "Kazakhstan", ioc: 'KAZ' },
  { code: 'LV', name: "Latvia", ioc: 'LAT' },
  { code: 'LT', name: "Lithuania", ioc: 'LTU' },
  { code: 'LU', name: "Luxembourg", ioc: 'LUX' },
  { code: 'MX', name: "Mexico", ioc: 'MEX' },
  { code: 'MD', name: "Moldova", ioc: 'MDA' },
  { code: 'MC', name: "Monaco", ioc: 'MON' },
  { code: 'ME', name: "Montenegro", ioc: 'MNE' },
  { code: 'MA', name: "Morocco", ioc: 'MAR' },
  { code: 'NL', name: "Netherlands", ioc: 'NED' },
  { code: 'NZ', name: "New Zealand", ioc: 'NZL' },
  { code: 'NO', name: "Norway", ioc: 'NOR' },
  { code: 'PY', name: "Paraguay", ioc: 'PAR' },
  { code: 'PE', name: "Peru", ioc: 'PER' },
  { code: 'PH', name: "Philippines", ioc: 'PHI' },
  { code: 'PL', name: "Poland", ioc: 'POL' },
  { code: 'PT', name: "Portugal", ioc: 'POR' },
  { code: 'RO', name: "Romania", ioc: 'ROU' },
  { code: 'RU', name: "Russia", ioc: 'RUS' },
  { code: 'RS', name: "Serbia", ioc: 'SRB' },
  { code: 'SG', name: "Singapore", ioc: 'SGP' },
  { code: 'SK', name: "Slovakia", ioc: 'SVK' },
  { code: 'SI', name: "Slovenia", ioc: 'SLO' },
  { code: 'ZA', name: "South Africa", ioc: 'RSA' },
  { code: 'KR', name: "South Korea", ioc: 'KOR' },
  { code: 'ES', name: "Spain", ioc: 'ESP' },
  { code: 'LK', name: "Sri Lanka", ioc: 'SRI' },
  { code: 'SE', name: "Sweden", ioc: 'SWE' },
  { code: 'CH', name: "Switzerland", ioc: 'SUI' },
  { code: 'TH', name: "Thailand", ioc: 'THA' },
  { code: 'TN', name: "Tunisia", ioc: 'TUN' },
  { code: 'TR', name: "Türkiye", ioc: 'TUR' },
  { code: 'UA', name: "Ukraine", ioc: 'UKR' },
  { code: 'AE', name: "United Arab Emirates", ioc: 'UAE' },
  { code: 'US', name: "United States", ioc: 'USA' },
  { code: 'UY', name: "Uruguay", ioc: 'URU' },
  { code: 'UZ', name: "Uzbekistan", ioc: 'UZB' },
  { code: 'VE', name: "Venezuela", ioc: 'VEN' },
  { code: 'VN', name: "Vietnam", ioc: 'VIE' },
];

if (typeof module !== 'undefined') {
  module.exports = COUNTRIES; // lets the Node.js server use this same list
}
